public class TestBST {
    public static void main(String[] args){
	BST t = new BST();
	System.out.println("isEmptyTree = " + t.isEmptyTree());
	Node xNode = new Node("Jane", 123456789);
	Node yNode = new Node("Joe", 934567890);
	Node zNode = new Node("Jack", 223452234);
	Node kNode = new Node("Jill", 934567856);
	Node aNode = new Node("Abe", 123456788);
	Node bNode = new Node("Beth", 934567898);
	Node cNode = new Node("Chuck", 223452238);
	Node dNode = new Node("Dot", 934567858);
	Node mNode = new Node("Mike", 723452237);
	Node nNode = new Node("Nick", 734567857);
	Node oNode = new Node("Otis", 734562222);
	t.insert(xNode);
	t.insert(yNode);
	t.insert(zNode);
	t.insert(kNode);
	t.traverse();
	t.printTree();
	t.insert(mNode);
	t.insert(nNode);
	System.out.println("search");
	System.out.println(t.search(6789).getName());
	System.out.println(t.search(7890).getName());
	System.out.println(t.search(2234).getName());
	System.out.println(t.search(7856).getName());
	t.traverse();
	t.printTree();
	System.out.println("searchFor 7890");
	System.out.println(t.search(7890).getName());
	System.out.println("delete6789");
	t.delete(xNode);
	t.traverse();
	t.printTree();
	System.out.println("delete2237");
	t.delete(mNode);
	t.traverse();
	t.printTree();
	System.out.println("delete7857");
	t.delete(nNode);
	t.traverse();
	t.printTree();
	System.out.println("insert6788");
	t.insert(aNode);
	t.traverse();
	t.printTree();
	System.out.println("insert2222");
	t.insert(oNode);
	t.traverse();
	t.printTree();
	System.out.println("delete2234");
	t.delete(zNode);
	t.traverse();
	t.printTree();
	System.out.println("isEmptyTree = " + t.isEmptyTree());
    }
}

